import express from 'express';
import cookieParser from 'cookie-parser';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import pinoHttpModule from 'pino-http';
const pinoHttp = (pinoHttpModule as any).default || pinoHttpModule;
import { query } from './config/db.js';
import { env } from './config/env.js';
import auth from './routes/auth.js';
import dashboard from './routes/dashboard.js';
import books from './routes/books.js';
import members from './routes/members.js';
import loans from './routes/loans.js';
import fines from './routes/fines.js';
import catalog from './routes/catalog.js';
import users from './routes/users.js';
import reports from './routes/reports.js';
import settings from './routes/settings.js';
import audit from './routes/audit.js';
import { errorHandler, notFound } from './middleware/error.js';

export const app = express();
app.set('trust proxy', 1);
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors({ origin: env.corsOrigin, credentials: true }));
app.use(express.json({ limit: '1mb' }));
app.use(cookieParser());
app.use(pinoHttp());
app.get('/health', async (_req, res) => { try { await query('SELECT 1'); res.json({ status:'ok', database:'ok', timestamp:new Date().toISOString() }); } catch { res.status(503).json({ status:'error', database:'unavailable' }); } });
app.use('/api/auth', rateLimit({ windowMs: 15*60*1000, limit: 30, standardHeaders: true, legacyHeaders: false }), auth);
app.use('/api/dashboard', dashboard);
app.use('/api/books', books);
app.use('/api/members', members);
app.use('/api/loans', loans);
app.use('/api/fines', fines);
app.use('/api/catalog', catalog);
app.use('/api/users', users);
app.use('/api/reports', reports);
app.use('/api/settings', settings);
app.use('/api/audit-logs', audit);
app.use(notFound);
app.use(errorHandler);
