import { Router } from 'express';
import { z } from 'zod';
import { query, withTransaction } from '../config/db.js';
import { requireAuth, requireRole } from '../middleware/auth.js';
import { AppError, asyncHandler, parseLimit, parsePage } from '../utils/http.js';
import { audit } from '../utils/audit.js';

const router=Router();router.use(requireAuth);
router.get('/',asyncHandler(async(req,res)=>{const page=parsePage(req.query.page);const limit=parseLimit(req.query.limit);const params:unknown[]=[];const clauses:string[]=[];if(req.query.status){params.push(String(req.query.status));clauses.push(`f.status=$${params.length}`);}if(req.query.search){params.push(`%${String(req.query.search)}%`);clauses.push(`(m.full_name ILIKE $${params.length} OR m.member_code ILIKE $${params.length})`);}const where=clauses.length?`WHERE ${clauses.join(' AND ')}`:'';const base=`FROM fines f JOIN members m ON m.id=f.member_id LEFT JOIN loans l ON l.id=f.loan_id`;const count=await query<{count:string}>(`SELECT count(*) ${base} ${where}`,params);const result=await query(`SELECT f.*,m.member_code,m.full_name member_name,COALESCE(f.amount-f.paid_amount,0) outstanding ${base} ${where} ORDER BY f.assessed_at DESC LIMIT $${params.length+1} OFFSET $${params.length+2}`,[...params,limit,(page-1)*limit]);res.json({data:result.rows,meta:{page,limit,total:Number(count.rows[0].count),pages:Math.ceil(Number(count.rows[0].count)/limit)}});}));
router.get('/:id/payments',asyncHandler(async(req,res)=>{const result=await query(`SELECT fp.*,u.name paid_by_name FROM fine_payments fp LEFT JOIN users u ON u.id=fp.paid_by WHERE fine_id=$1 ORDER BY paid_at DESC`,[String(req.params.id)]);res.json({data:result.rows});}));
router.post('/:id/payment',requireRole('admin','librarian'),asyncHandler(async(req,res)=>{const data=z.object({amount:z.coerce.number().positive(),notes:z.string().max(500).optional()}).parse(req.body);const result=await withTransaction(async(client)=>{const fine=await client.query('SELECT * FROM fines WHERE id=$1 FOR UPDATE',[String(req.params.id)]);if(!fine.rowCount)throw new AppError(404,'Fine not found.','NOT_FOUND');const outstanding=Number(fine.rows[0].amount)-Number(fine.rows[0].paid_amount);if(data.amount>outstanding+.001)throw new AppError(400,`Payment cannot exceed the outstanding balance of ${outstanding.toFixed(2)}.`,'PAYMENT_TOO_LARGE');const payment=await client.query(`INSERT INTO fine_payments(fine_id,amount,paid_by,notes) VALUES($1,$2,$3,$4) RETURNING *`,[String(req.params.id),data.amount,req.user!.id,data.notes||null]);const paid=Number(fine.rows[0].paid_amount)+data.amount;await client.query(`UPDATE fines SET paid_amount=$1,status=$2 WHERE id=$3`,[paid,paid>=Number(fine.rows[0].amount)?'paid':'partially_paid',String(req.params.id)]);await audit({userId:req.user!.id,action:'paid',entity:'fine',entityId:String(req.params.id),details:{amount:data.amount},ip:req.ip},client);return payment.rows[0];});res.status(201).json({data:result});}));
router.post('/',requireRole('admin','librarian'),asyncHandler(async(req,res)=>{const data=z.object({member_id:z.string().uuid(),amount:z.coerce.number().positive(),notes:z.string().max(500).optional()}).parse(req.body);const result=await query(`INSERT INTO fines(member_id,type,amount,notes) VALUES($1,'manual',$2,$3) RETURNING *`,[data.member_id,data.amount,data.notes||null]);await audit({userId:req.user!.id,action:'created',entity:'fine',entityId:result.rows[0].id,details:{amount:data.amount,type:'manual'},ip:req.ip});res.status(201).json({data:result.rows[0]});}));
export default router;
