import { Router } from 'express';
import { z } from 'zod';
import { query, withTransaction } from '../config/db.js';
import { requireAuth, requireRole } from '../middleware/auth.js';
import { AppError, asyncHandler, parseLimit, parsePage } from '../utils/http.js';
import { audit } from '../utils/audit.js';

const router = Router(); router.use(requireAuth);
const memberInput = z.object({ full_name:z.string().trim().min(2).max(160), email:z.string().email().optional().nullable(), phone:z.string().max(40).optional().nullable(), address:z.string().max(500).optional().nullable(), date_of_birth:z.string().optional().nullable(), membership_type:z.enum(['Student','Staff','General Member']).default('General Member'), membership_expiry_date:z.string().min(10), status:z.enum(['active','inactive','expired']).default('active'), profile_photo:z.string().url().optional().nullable(), notes:z.string().max(2000).optional().nullable() });
const memberSelect = `m.*, COALESCE((SELECT count(*) FROM loans l WHERE l.member_id=m.id AND l.status='active'),0)::int current_loans, COALESCE((SELECT sum(f.amount-f.paid_amount) FROM fines f WHERE f.member_id=m.id AND f.status <> 'paid'),0) outstanding_fines`;
router.get('/', asyncHandler(async (req,res)=>{ const search=String(req.query.search||'').trim(); const page=parsePage(req.query.page); const limit=parseLimit(req.query.limit); const params:unknown[]=[]; const clauses:string[]=[]; if(search){params.push(`%${search}%`);clauses.push(`(m.full_name ILIKE $1 OR m.member_code ILIKE $1 OR m.email ILIKE $1 OR m.phone ILIKE $1)`);} if(req.query.status){params.push(String(req.query.status));clauses.push(`m.status=$${params.length}`);} const where=clauses.length?`WHERE ${clauses.join(' AND ')}`:''; const count=await query<{count:string}>(`SELECT count(*) FROM members m ${where}`,params); const result=await query(`${memberSelect} FROM members m ${where} ORDER BY m.created_at DESC LIMIT $${params.length+1} OFFSET $${params.length+2}`,[...params,limit,(page-1)*limit]); res.json({data:result.rows,meta:{page,limit,total:Number(count.rows[0].count),pages:Math.ceil(Number(count.rows[0].count)/limit)}}); }));
router.get('/:id', asyncHandler(async(req,res)=>{ const member=await query(`${memberSelect} FROM members m WHERE m.id=$1`,[String(req.params.id)]); if(!member.rowCount)throw new AppError(404,'Member not found.','NOT_FOUND'); const loans=await query(`SELECT l.*,b.title,b.book_code,c.barcode FROM loans l JOIN book_copies c ON c.id=l.copy_id JOIN books b ON b.id=c.book_id WHERE l.member_id=$1 ORDER BY l.created_at DESC LIMIT 50`,[String(req.params.id)]); const fines=await query(`SELECT f.*,COALESCE((SELECT sum(amount) FROM fine_payments fp WHERE fp.fine_id=f.id),0) paid_total FROM fines f WHERE f.member_id=$1 ORDER BY f.assessed_at DESC`,[String(req.params.id)]); res.json({data:{...member.rows[0],loans:loans.rows,fines:fines.rows}}); }));
router.post('/', requireRole('admin','librarian'), asyncHandler(async(req,res)=>{const data=memberInput.parse(req.body); const result=await withTransaction(async(client)=>{await client.query('SELECT pg_advisory_xact_lock(913402)');const code=await (async()=>{const r=await client.query<{code:string}>(`SELECT 'MEM-' || lpad((COALESCE((SELECT max(NULLIF(regexp_replace(member_code,'[^0-9]','','g'),'')::int) FROM members),0)+1)::text,5,'0') code`);return r.rows[0].code;})(); const member=await client.query(`INSERT INTO members(member_code,full_name,email,phone,address,date_of_birth,membership_type,membership_expiry_date,status,profile_photo,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[code,data.full_name,data.email||null,data.phone||null,data.address||null,data.date_of_birth||null,data.membership_type,data.membership_expiry_date,data.status,data.profile_photo||null,data.notes||null]); await audit({userId:req.user!.id,action:'created',entity:'member',entityId:member.rows[0].id,details:{member_code:code},ip:req.ip},client); return member.rows[0];}); res.status(201).json({data:result});}));
router.put('/:id', requireRole('admin','librarian'), asyncHandler(async(req,res)=>{const data=memberInput.partial().parse(req.body); const keys=Object.entries(data) as Array<[string,unknown]>; if(!keys.length) throw new AppError(400,'No changes submitted.','VALIDATION_ERROR'); const result=await query(`UPDATE members SET ${keys.map(([key],i)=>`${key}=$${i+1}`).join(',')},updated_at=now() WHERE id=$${keys.length+1} RETURNING *`,[...keys.map(([,v])=>v??null),String(req.params.id)]); if(!result.rowCount)throw new AppError(404,'Member not found.','NOT_FOUND'); await audit({userId:req.user!.id,action:'updated',entity:'member',entityId:String(req.params.id),details:{fields:keys.map(([k])=>k)},ip:req.ip});res.json({data:result.rows[0]});}));
router.delete('/:id', requireRole('admin','librarian'), asyncHandler(async(req,res)=>{const active=await query('SELECT 1 FROM loans WHERE member_id=$1 AND status=\'active\'',[String(req.params.id)]);if(active.rowCount)throw new AppError(400,'This member has active loans and cannot be deactivated.','ACTIVE_LOANS');const result=await query(`UPDATE members SET status='inactive',updated_at=now() WHERE id=$1 RETURNING id`,[String(req.params.id)]);if(!result.rowCount)throw new AppError(404,'Member not found.','NOT_FOUND');await audit({userId:req.user!.id,action:'deactivated',entity:'member',entityId:String(req.params.id),ip:req.ip});res.json({data:{success:true}});}));
router.post('/:id/renew', requireRole('admin','librarian'), asyncHandler(async(req,res)=>{const months=z.number().int().min(1).max(36).default(12).parse(Number(req.body?.months)||12);const result=await query(`UPDATE members SET membership_expiry_date=GREATEST(membership_expiry_date,CURRENT_DATE) + ($1 || ' months')::interval,status='active',updated_at=now() WHERE id=$2 RETURNING *`,[months,String(req.params.id)]);if(!result.rowCount)throw new AppError(404,'Member not found.','NOT_FOUND');res.json({data:result.rows[0]});}));
export default router;
